# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
